### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#16]
This is the release plan I have in mind. 
# Version 1.0.0

Version 1 is for swapping into existing project, and should not require any changes. Exceptions will be made, if they actually catch real errors or potential problems, and they should preferably be auto fixable.

eslint@2 adds auto fixing to numerous new rules, so I'd like to get that in as well.
- [x] add sublime setup #8 
- [x] eslint 2
- [x] disable single quote rule
- [x] space after case/return #13 
# Version 2.0.0

Version 2 will contain improvements to the existing onelint configuration allowed by the change to eslint.
- [ ] enable single quote rule #3
- [ ] enable node.js callback rule #4

**Comment by gustavnikolaj** [comment]
Down to just below 40 errors on a certain large internal project :-) All of which are either legitimate problems, or cases of code that diverge from our normal style. (After auto fixing stuff like indentation issues)
