### ISSUE TITLE
Migrate jscs options

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#2]
- [x] requireSpaceAfterKeywords: if
- [x] requireSpaceAfterKeywords: else
- [x] requireSpaceAfterKeywords: for
- [x] requireSpaceAfterKeywords: while
- [x] requireSpaceAfterKeywords: do
- [x] requireSpaceAfterKeywords: switch
- [x] ~~requireSpaceAfterKeywords: case~~ (not until eslint@2 - see #13)
- [x] ~~requireSpaceAfterKeywords: return~~ (not until eslint@2 - see #13)
- [x] requireSpaceAfterKeywords: try
- [x] requireSpaceAfterKeywords: catch
- [x] requireSpaceAfterKeywords: function
- [x] ~~requireSpaceAfterKeywords: typeof~~ (not until eslint@2 - see #13)

---
- [x] requireCurlyBraces: if
- [x]         requireCurlyBraces: else
- [x]         requireCurlyBraces: for
- [x]         requireCurlyBraces: while
- [x]         requireCurlyBraces: do
- [x] ~~requireCurlyBraces: switch~~
- [x] ~~requireCurlyBraces: catch~~
- [x] ~~requireCurlyBraces: function~~

---
- [x] disallowSpacesInNamedFunctionExpression
- [x] disallowSpacesInNamedFunctionExpression: beforeOpeningCurlyBrace: true

---
- [x] requireSpacesInAnonymousFunctionExpression
- [x] requireSpacesInAnonymousFunctionExpression: beforeOpeningRoundBrace: true
- [x] requireSpacesInAnonymousFunctionExpression: beforeOpeningCurlyBrace: true

---
- [x] requireSpaceBeforeBlockStatements: true

---
- [x] requireParenthesesAroundIIFE: true

---
- [x] requireSpacesInConditionalExpression: true

---
- [x] disallowSpacesInNamedFunctionExpression
- [x] disallowSpacesInNamedFunctionExpression: beforeOpeningRoundBrace: true

---
- [x] disallowSpacesInFunctionDeclaration
- [x] disallowSpacesInFunctionDeclaration: beforeOpeningRoundBrace: true

---
- [x] requireBlocksOnNewline: true

---
- [x] disallowEmptyBlocks: true

---
- [x] disallowSpacesInsideParentheses: true

---
- [x] requireCommaBeforeLineBreak: true

---
- [x] "disallowSpaceAfterPrefixUnaryOperators": true,
- [x] "disallowSpaceBeforePostfixUnaryOperators": true,
- [x]  "disallowSpaceBeforeBinaryOperators": [","],
- [x] "disallowSpacesInCallExpression": true
- [x] "requireSpaceBeforeBinaryOperators": true
- [x] "requireSpaceAfterBinaryOperators": true

---
- [x] "disallowKeywords": ["with"]

---
- [x]  "validateIndentation": 4
- [x]     "disallowMixedSpacesAndTabs": "smart"
- [x]  "disallowTrailingWhitespace": true
- [x]     "disallowTrailingComma": true
- [x]     ~~"disallowKeywordsOnNewLine": ["else"]~~ (covered by brace-style)
- [x]     "requireLineFeedAtFileEnd": true
- [x]     "requireCapitalizedConstructors": true
- [x]     "disallowNewlineBeforeBlockStatements": true
- [x]     "requireCamelCaseOrUpperCaseIdentifiers": true
- [x]     "requireDotNotation": true
- [x]     "validateParameterSeparator": ", "
- [x]     "safeContextKeyword": ["that"]

---
- [x] excludeFiles: node_modules

**Comment by gustavnikolaj** [comment]
https://github.com/brenolf/polyjuice/blob/master/lib/dictionaries/jscs.js
